"use client";

import { useEffect, useMemo } from "react";
import { CalendarClock, RefreshCw, ShieldCheck, TrendingDown, TrendingUp } from "lucide-react";
import { useWalletStore } from "@/store/finance/wallet-store";

export default function DollarShieldPage() {
  const { fiatWallets, isLoading, fetchWallets } = useWalletStore();
  useEffect(() => { void fetchWallets(); }, [fetchWallets]);
  const brlWallet = useMemo(() => (fiatWallets || []).find((wallet: any) => String(wallet.currency || "").toUpperCase() === "BRL"), [fiatWallets]);
  const brlBalance = brlWallet ? Number(brlWallet.balance ?? brlWallet.amount ?? 0) : null;
  const hasLiveWallet = brlBalance !== null && Number.isFinite(brlBalance);

  return (
    <div className="mx-auto max-w-[1180px] space-y-5">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#2c78b6]"><ShieldCheck className="h-3.5 w-3.5" /> Wealth protection</div><h1 className="text-2xl font-bold tracking-tight text-[#182536]">Dollar Shield</h1><p className="mt-1 text-xs text-[#7a8696]">Protect your savings from BRL inflation — automatic conversion to stablecoins.</p></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-[10px] font-semibold text-amber-700">Safe preview · no automatic conversion</span></div>
      <div className="flex items-center justify-between rounded-md border border-[#dfe5ec] bg-white px-4 py-3 text-[11px] text-[#667487]"><span>{isLoading ? "Refreshing BRL wallet data…" : hasLiveWallet ? "BRL wallet connected. Historical shield data is not configured." : "Connect the backend to load BRL wallet data."}</span><button type="button" onClick={() => void fetchWallets()} className="inline-flex items-center gap-1.5 rounded border border-[#dbe2e9] px-3 py-1.5 text-[10px] font-semibold text-[#536173] hover:bg-[#f8fafc]"><RefreshCw className="h-3 w-3" />Refresh</button></div>
      <section className="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
        <article className="rounded-md border border-[#dfe5ec] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold text-[#263548]">Purchasing Power — Last 12 Months</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Historical BRL versus stablecoin performance</p></div><TrendingDown className="h-4 w-4 text-rose-400" /></div><div className="mt-5 flex h-[190px] items-center justify-center rounded border border-dashed border-[#dfe5ec] bg-[#fafbfd] px-8 text-center"><div><p className="text-sm font-semibold text-[#536173]">Historical data unavailable</p><p className="mt-2 text-[10px] leading-5 text-[#8b96a4]">This chart will populate when the inflation and conversion history API is enabled. No indicative values are shown as account performance.</p></div></div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-[#718094]"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-[#cbd5df]" />BRL historical series pending</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-[#9ccdb6]" />Shielded series pending</span></div></article>
        <article className="rounded-md border border-[#dfe5ec] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold text-[#263548]">Active DCA Plan</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Automatic weekly conversion</p></div><CalendarClock className="h-4 w-4 text-[#2876b3]" /></div><div className="mx-auto mt-7 flex h-32 w-32 items-center justify-center rounded-full border-8 border-[#e8edf1]"><div className="flex h-24 w-24 flex-col items-center justify-center rounded-full bg-white text-center"><strong className="text-sm font-bold text-[#263548]">Not active</strong><span className="mt-1 text-[9px] text-[#8b96a4]">API required</span></div></div><p className="mt-4 text-center text-[11px] font-semibold text-[#354154]">{hasLiveWallet ? `BRL wallet: ${brlBalance.toLocaleString(undefined, { maximumFractionDigits: 2 })}` : "BRL wallet balance —"}</p><p className="mt-1 text-center text-[10px] text-[#8b96a4]">No recurring buy has been scheduled</p></article>
      </section>
      <section className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#263548]">Auto-Buy Timeline</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Completed and scheduled conversions</p></div><TrendingUp className="h-4 w-4 text-emerald-500" /></div><div className="flex items-center gap-3 px-5 py-8"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#edf5fb] text-[#2876b3]"><CalendarClock className="h-4 w-4" /></div><div className="flex-1"><p className="text-xs font-semibold text-[#354154]">No conversion history available</p><p className="mt-1 text-[10px] text-[#8b96a4]">The timeline will appear after the Dollar Shield API is connected.</p></div><span className="rounded-full bg-[#eef1f5] px-2 py-1 text-[9px] font-bold text-[#7b8795]">PENDING</span></div></section>
      <p className="text-[10px] text-[#8b96a4]">Dollar Shield is currently a safe product surface. No conversion, payment, recurring purchase, or financial transaction is executed from this screen.</p>
    </div>
  );
}
