"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Gift, Smartphone, Ticket, Zap } from "lucide-react";
import { $fetch } from "@/lib/api";
type Product = { id: string; category: string; name: string; description?: string; price: number; currency: string };
const icons: Record<string, typeof Gift> = { GIFT_CARD: Gift, UTILITY: Zap, TICKET: Ticket, ESIM: Smartphone, DIGITAL: Gift };
export default function DigitalServicesPanel() {
  const [products, setProducts] = useState<Product[]>([]); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void (async () => { const response = await $fetch<{ products: Product[] }>({ url: "/api/market/products", silent: true }); if (!response.error) setProducts(response.data?.products || []); })(); }, []);
  const checkout = async (productId: string) => { setBusy(productId); const response = await $fetch({ url: "/api/market/orders", method: "POST", body: { productId, quantity: 1 }, successMessage: "Digital product purchased" }); if (!response.error) setMessage("Order completed. Your digital delivery is available in the order details."); setBusy(null); };
  return <section className="border-b border-slate-200/80 bg-white px-5 py-10 sm:px-8"><div className="mx-auto max-w-[1320px]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#047857]">Digital services</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-slate-950">Everyday utilities in one checkout.</h2><p className="mt-2 max-w-2xl text-sm text-slate-500">Purchase gift cards, utility payments, tickets, eSIM profiles, and other digital products directly from your fiat wallet.</p></div>{message && <span className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" />{message}</span>}</div><div className="mt-6 grid gap-3 md:grid-cols-3">{products.map((product) => { const Icon = icons[product.category] || Gift; return <article key={product.id} className="rounded-xl border border-slate-200/80 bg-slate-50 p-4"><div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700"><Icon className="h-4 w-4" /></span><span className="text-xs font-bold text-slate-950">{product.currency} {Number(product.price).toFixed(2)}</span></div><p className="mt-4 text-sm font-semibold text-slate-950">{product.name}</p><p className="mt-1 min-h-8 text-xs leading-4 text-slate-500">{product.description}</p><button disabled={busy === product.id} onClick={() => void checkout(product.id)} className="mt-4 w-full rounded-lg bg-[#047857] px-3 py-2 text-xs font-bold text-white transition hover:bg-[#059669] disabled:opacity-50">{busy === product.id ? "Processing…" : "Buy now"}</button></article>; })}</div></div></section>;
}
