"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, CircleDollarSign, Eye, EyeOff, MoreHorizontal, Plus, TrendingUp } from "lucide-react";

const watchlist = [["Bitcoin", "BTC", "—", "—", "#f59e0b"], ["Ethereum", "ETH", "—", "—", "#6366f1"], ["Solana", "SOL", "—", "—", "#10b981"], ["XRP", "XRP", "—", "—", "#64748b"]];

export default function DashboardPage() {
  const [hidden, setHidden] = useState(false);
  const display = (value: string) => hidden ? "••••••" : value;

  return (
    <div className="mx-auto max-w-[1180px] space-y-5">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#2c78b6]">Overview</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-[#182536]">Dashboard</h1><p className="mt-1 text-xs text-[#7a8696]">Welcome back. Here’s what is happening with your portfolio.</p></div><div className="flex gap-2"><Link href="/en/finance/deposit" className="inline-flex items-center gap-2 rounded-md bg-[#2876b3] px-3 py-2 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5" />Add funds</Link><button type="button" onClick={() => setHidden((value) => !value)} className="inline-flex items-center gap-2 rounded-md border border-[#dce3ea] bg-white px-3 py-2 text-xs font-medium text-[#5f6d7e]">{hidden ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}{hidden ? "Show balances" : "Hide balances"}</button></div></div>
      <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-[11px] text-amber-800">Dashboard figures are paper-mode preview values until the backend and database are connected.</div>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["TOTAL PORTFOLIO VALUE", "—", "Live data unavailable", "#7c8795"], ["AVAILABLE BALANCE", "—", "Live data unavailable", "#7c8795"], ["IN ORDERS", "—", "Live data unavailable", "#7c8795"], ["EARNED", "—", "Live data unavailable", "#7c8795"]].map(([label, value, change, color]) => <div key={label} className="rounded-md border border-[#dfe5ec] bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><p className="text-[9px] font-semibold tracking-[0.08em] text-[#8b96a4]">{label}</p><p className="mt-2 text-xl font-bold text-[#253348]">{hidden ? "••••••" : value}</p><p className="mt-1 text-[10px] font-semibold" style={{ color }}>{hidden ? "Hidden" : change}</p></div>)}</section>
      <section className="grid gap-5 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#263548]">Portfolio Performance</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Your portfolio value over time</p></div><div className="flex gap-1 text-[10px] text-[#8b96a4]"><button className="rounded bg-[#eaf3fb] px-2 py-1 font-semibold text-[#2876b3]">7D</button><button className="px-2 py-1">1M</button><button className="px-2 py-1">1Y</button></div></div><div className="relative h-[230px] p-5"><div className="absolute inset-x-8 bottom-9 top-8 bg-[linear-gradient(to_bottom,transparent_49%,#edf1f5_50%,transparent_51%),linear-gradient(to_right,transparent_24%,#f1f3f6_25%,transparent_26%,transparent_49%,#f1f3f6_50%,transparent_51%,transparent_74%,#f1f3f6_75%,transparent_76%)]" /><svg viewBox="0 0 800 220" className="relative h-full w-full" preserveAspectRatio="none"><path d="M0 174 C90 165 110 142 190 156 S280 145 330 120 S400 135 470 105 S560 118 620 72 S700 90 800 38 L800 220 L0 220 Z" fill="url(#area)" /><path d="M0 174 C90 165 110 142 190 156 S280 145 330 120 S400 135 470 105 S560 118 620 72 S700 90 800 38" fill="none" stroke="#2876b3" strokeWidth="3" /><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5da1d0" stopOpacity=".28" /><stop offset="1" stopColor="#5da1d0" stopOpacity="0" /></linearGradient></defs></svg></div></div><div className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#263548]">Market Watchlist</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Your tracked assets</p></div><Link href="/en/market" className="text-[10px] font-semibold text-[#2876b3]">View all</Link></div><div className="divide-y divide-[#f0f2f5]">{watchlist.map(([name, symbol, price, change, color]) => <Link href={`/en/trade?symbol=${symbol}USDT`} key={symbol} className="flex items-center justify-between px-5 py-3 hover:bg-[#fafbfd]"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full text-[10px] font-bold text-white" style={{ backgroundColor: color }}>{symbol[0]}</span><div><p className="text-xs font-semibold text-[#354154]">{name}</p><p className="text-[9px] text-[#9aa4b1]">{symbol}/USDT</p></div></div><div className="text-right"><p className="text-xs font-semibold text-[#354154]">{display(price)}</p><p className={`text-[10px] font-semibold ${change.startsWith("-") ? "text-rose-500" : "text-emerald-600"}`}>{hidden ? "—" : change}</p></div></Link>)}</div></div></section>
      <section className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><h2 className="text-sm font-semibold text-[#263548]">Quick actions</h2><MoreHorizontal className="h-4 w-4 text-[#9aa4b1]" /></div><div className="grid gap-3 p-4 sm:grid-cols-4"><Link href="/en/finance/deposit" className="flex items-center gap-3 rounded-md border border-[#e5e9ee] p-3 text-xs font-medium text-[#526174] hover:border-[#9fc8e5]"><ArrowDownToLine className="h-4 w-4 text-[#2876b3]" />Deposit</Link><Link href="/en/finance/withdraw" className="flex items-center gap-3 rounded-md border border-[#e5e9ee] p-3 text-xs font-medium text-[#526174] hover:border-[#9fc8e5]"><ArrowUpFromLine className="h-4 w-4 text-[#2876b3]" />Withdraw</Link><Link href="/en/trade" className="flex items-center gap-3 rounded-md border border-[#e5e9ee] p-3 text-xs font-medium text-[#526174] hover:border-[#9fc8e5]"><TrendingUp className="h-4 w-4 text-[#2876b3]" />Trade now</Link><Link href="/en/staking" className="flex items-center gap-3 rounded-md border border-[#e5e9ee] p-3 text-xs font-medium text-[#526174] hover:border-[#9fc8e5]"><CircleDollarSign className="h-4 w-4 text-[#2876b3]" />Earn rewards</Link></div></section>
    </div>
  );
}
