"use client";
import { useEffect, useState } from "react";
import { Copy, QrCode, ShieldCheck } from "lucide-react";
import { $fetch } from "@/lib/api";
type Account = { currency: string; bankName?: string; accountType?: string; routingNumber?: string; accountNumber?: string; iban?: string; bic?: string; sortCode?: string; countryCode?: string };
type DepositWallet = { network: string; address: string; qrCode: string };
export default function WalletAccountsPanel() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [usdt, setUsdt] = useState<Record<string, DepositWallet>>({});
  useEffect(() => { void (async () => { const response = await $fetch<{ accounts: Account[]; usdt: Record<string, DepositWallet> }>({ url: "/api/finance/virtual-accounts", silent: true }); if (!response.error && response.data) { setAccounts(response.data.accounts || []); setUsdt(response.data.usdt || {}); } })(); }, []);
  const value = (account: Account) => account.currency === "EUR" ? [["IBAN", account.iban], ["BIC / SWIFT", account.bic]] : account.currency === "GBP" ? [["Sort code", account.sortCode], ["Account number", account.accountNumber]] : [["Routing number", account.routingNumber], ["Account number", account.accountNumber], ["Account type", account.accountType]];
  return <section className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><article className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#263548]">Virtual bank accounts</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Dedicated details generated for your KYC country.</p></div><ShieldCheck className="h-4 w-4 text-emerald-600" /></div><div className="grid gap-3 p-4 sm:grid-cols-2">{accounts.map((account) => <div key={account.currency} className="rounded-md border border-[#e5e9ee] p-3"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#354154]">{account.currency === "LOCAL" ? `Local (${account.countryCode})` : account.currency}</span><span className="text-[9px] font-semibold text-emerald-600">ACTIVE</span></div><p className="mt-1 text-[10px] text-[#8b96a4]">{account.bankName}</p><div className="mt-3 space-y-1.5">{value(account).map(([label, item]) => item && <div key={label} className="flex items-center justify-between gap-2 text-[10px]"><span className="text-[#8b96a4]">{label}</span><span className="flex items-center gap-1 font-mono font-semibold text-[#526174]">{item}<Copy className="h-3 w-3 text-[#9aa4b1]" /></span></div>)}</div></div>)}</div></article><article className="rounded-md border border-[#dfe5ec] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#263548]">USDT deposit wallets</h2><p className="mt-1 text-[10px] text-[#8b96a4]">Choose the network before sending funds.</p></div><QrCode className="h-4 w-4 text-[#2876b3]" /></div><div className="divide-y divide-[#f0f2f5]">{Object.entries(usdt).map(([network, wallet]) => <div key={network} className="flex items-center gap-3 px-5 py-4"><img src={wallet.qrCode} alt={`${network} USDT deposit QR code`} className="h-16 w-16 rounded border border-[#e5e9ee]" /><div className="min-w-0"><p className="text-xs font-bold text-[#354154]">{network}</p><p className="mt-1 break-all font-mono text-[9px] text-[#7a8696]">{wallet.address}</p><button className="mt-2 text-[10px] font-bold text-[#2876b3]">Copy address</button></div></div>)}</div></article></section>;
}
