"use client";

import { useMemo, useState } from "react";
import { ArrowDown, ArrowRight, CheckCircle2, Clock3, Globe2, LockKeyhole, ShieldCheck } from "lucide-react";

const corridors = { "AR-CO": { from: "Argentina", fromCode: "ARS", to: "Colombia", toCode: "COP", rate: 2.42, fee: 0 }, "BR-AR": { from: "Brazil", fromCode: "BRL", to: "Argentina", toCode: "ARS", rate: 5.18, fee: 0.18 }, "BR-CO": { from: "Brazil", fromCode: "BRL", to: "Colombia", toCode: "COP", rate: 0.0081, fee: 0.12 } } as const;

export default function SendMoneyPage() {
  const [corridorKey, setCorridorKey] = useState<keyof typeof corridors>("AR-CO");
  const [amount, setAmount] = useState("50000");
  const corridor = corridors[corridorKey];
  const result = useMemo(() => Number(amount || 0) * corridor.rate, [amount, corridor.rate]);
  return <div className="mx-auto max-w-[980px] space-y-5"><div className="text-center"><div className="mb-2 flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#2876b3]"><Globe2 className="h-3.5 w-3.5" /> Cross-border settlement</div><h1 className="text-3xl font-bold tracking-tight text-[#182536]">Send Money</h1><p className="mt-1 text-xs text-[#7a8696]">As easy as sending a text — anywhere in LATAM.</p></div>
    <div className="flex flex-wrap items-center justify-center gap-3"><select aria-label="Select corridor" value={corridorKey} onChange={(event) => setCorridorKey(event.target.value as keyof typeof corridors)} className="h-9 rounded-md border border-[#dfe5ec] bg-white px-3 text-xs font-semibold text-[#354154] outline-none"><option value="AR-CO">🇦🇷 Argentina</option><option value="BR-AR">🇧🇷 Brazil</option><option value="BR-CO">🇧🇷 Brazil</option></select><ArrowRight className="h-4 w-4 text-[#2876b3]" /><span className="rounded-md border border-[#dfe5ec] bg-white px-3 py-2 text-xs font-semibold text-[#354154]">{corridor.to === "Colombia" ? "🇨🇴 Colombia" : "🇦🇷 Argentina"}</span></div>
    <section className="rounded-md border border-[#dfe5ec] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="rounded border border-[#dfe5ec] bg-[#f5f7fa] px-5 py-6 text-center"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#7d8998]">You send</p><div className="mt-1 flex items-center justify-center gap-3"><span className="text-lg text-[#718094]">$</span><input aria-label="Amount to send" value={amount} onChange={(event) => setAmount(event.target.value.replace(/[^0-9.]/g, ""))} className="w-48 bg-transparent text-center text-4xl font-bold tracking-tight text-[#182536] outline-none" /><span className="text-sm font-bold text-[#718094]">{corridor.fromCode}</span></div><p className="mt-3 text-xs text-[#7d8998]">Recipient gets</p><p className="mt-1 text-2xl font-bold text-[#21a86c]">{result.toLocaleString("en-US", { maximumFractionDigits: 2 })} {corridor.toCode}</p></div><div className="mt-4 divide-y divide-[#edf0f4] rounded border border-[#e4e9ef] bg-white text-xs"><div className="flex justify-between px-4 py-3 text-[#667487]"><span>Exchange rate</span><strong className="text-[#354154]">1 {corridor.fromCode} = {corridor.rate} {corridor.toCode}</strong></div><div className="flex justify-between px-4 py-3 text-[#667487]"><span>Quatava fee</span><strong className="text-[#21a86c]">{corridor.fee === 0 ? "$0.00 (0%)" : `${corridor.fee}%`}</strong></div><div className="flex justify-between px-4 py-3 text-[#667487]"><span>Estimated delivery</span><strong className="inline-flex items-center gap-1 text-[#354154]"><Clock3 className="h-3.5 w-3.5 text-[#2876b3]" />Under 10 minutes</strong></div></div><button className="mt-4 h-11 w-full rounded-md bg-[#2876b3] text-xs font-bold text-white transition hover:bg-[#1f659b]">Continue to recipient</button></section>
    <section className="grid gap-3 text-[10px] text-[#718094] sm:grid-cols-3"><div className="flex items-center gap-2 rounded border border-[#e5eaf0] bg-white px-4 py-3"><LockKeyhole className="h-4 w-4 text-[#2876b3]" />Locked quote before confirmation</div><div className="flex items-center gap-2 rounded border border-[#e5eaf0] bg-white px-4 py-3"><CheckCircle2 className="h-4 w-4 text-emerald-500" />Proof of payout included</div><div className="flex items-center gap-2 rounded border border-[#e5eaf0] bg-white px-4 py-3"><ShieldCheck className="h-4 w-4 text-emerald-500" />Transparent exception support</div></section><p className="text-center text-[10px] text-[#8b96a4]">Indicative preview only. Delivery, supported currencies, and fees depend on partner availability, verification, and local rules.</p>
  </div>;
}
